[package]
name = "ecdsa_nonce_reuse"
version = "0.1.0"
edition = "2021"

[dependencies]
p256 = { version = "0.11", features = ["pkcs8"] }
sha2 = "0.10"
rand_core = "0.6"
hex = "0.4"
num-bigint = "0.4.6"
